# Generated by Django 4.2.13 on 2024-05-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country_code',
            new_name='phone_country_code',
        ),
    ]
