# Generated by Django 4.2.13 on 2024-05-31 16:54

from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_kindproduct_name_subkindproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, null=True)),
                ('short_description', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('description', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('views', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image_principal', thumbnails.fields.ImageField(blank=True, null=True, upload_to='product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category')),
                ('kind_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_kind', to='product.kindproduct')),
                ('sub_kind_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subkind', to='product.subkindproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
